name: crohnsmodeling
channels:

conda-forge
dependencies:

python=3.11

numpy

scipy

matplotlib

jupyterlab

pandas

numba

pytest

notebook

pytorch

pip

pip:

mesa

pymc3

optuna

numpyro

torchdiffeq
